import {getTimeString} from '@src/common/helpers/date';
import {addDashToPhoneNumber} from '@src/common/helpers/PhoneNumberParser';
import {stringSorter} from '@src/common/helpers/sorter';
export const orderItemColumns = [
  {
    title: '상품별 주문 번호',
    dataIndex: 'merchantUid',
    key: 'merchantUid',
    sorter: (a, b) => b.merchantUid - a.merchantUid,
    width: 140,
    ellipsis: true,
  },
  {
    title: '주문 묶음별 번호',
    dataIndex: 'orderMerchantUid',
    key: 'orderMerchantUid',
    sorter: (a, b) => b.orderMerchantUid - a.orderMerchantUid,
    width: 120,
    ellipsis: true,
  },
  {
    title: '주문 일시',
    dataIndex: 'paidAt',
    key: 'paidAt',
    render: (value) => <div>{getTimeString(value)}</div>,
    sorter: (a, b) => stringSorter(b.paidAt, a.paidAt),
    width: 100,
    ellipsis: true,
  },
  {
    title: '주문상태',
    dataIndex: 'status',
    key: 'status',
    sorter: (a, b) => stringSorter(b.status, a.status),
    width: 90,
    ellipsis: true,
  },
  {
    title: '클레임 상태',
    dataIndex: 'claimStatus',
    key: 'claimStatus',
    sorter: (a, b) => stringSorter(b.claimStatus, a.claimStatus),
    width: 140,
    ellipsis: true,
  },
  {
    title: '상품명',
    dataIndex: 'itemName',
    key: 'itemName',
    sorter: (a, b) => stringSorter(b.itemName, a.itemName),
    width: 200,
    ellipsis: true,
  },
  {
    title: '옵션명',
    dataIndex: 'productVariantName',
    key: 'productVariantName',
    sorter: (a, b) => stringSorter(b.productVariantName, a.productVariantName),
    width: 200,
    ellipsis: true,
  },
  {
    title: '수량',
    dataIndex: 'quantity',
    key: 'quantity',
    sorter: (a, b) => b.quantity - a.quantity,
    width: 75,
    ellipsis: true,
  },
  {
    title: '수취인명',
    dataIndex: 'order.receiver.name',
    key: 'order.receiver.name',
    width: 75,
    ellipsis: true,
  },
  {
    title: '수취인 연락처',
    dataIndex: 'order.receiver.phoneNumber',
    key: 'order.receiver.phoneNumber',
    render: (value) => <div>{value ? addDashToPhoneNumber(value) : null}</div>,
    width: 75,
    ellipsis: true,
  },
  {
    title: '구매자명',
    dataIndex: 'order.buyer.name',
    key: 'order.buyer.name',
    width: 75,
    ellipsis: true,
  },
  {
    title: '구매자 연락처',
    dataIndex: 'order.buyer.phoneNumber',
    key: 'order.buyer.phoneNumber',
    render: (value) => <div>{value ? addDashToPhoneNumber(value) : null}</div>,
    width: 75,
    ellipsis: true,
  },
  {
    title: '구매자 이메일',
    dataIndex: 'order.buyer.email',
    key: 'order.buyer.email',
    width: 75,
    ellipsis: true,
  },
];
