import {Button} from 'antd';

import {getDateTimeStrings} from '@src/lib/DateParser';
import {addDashToPhoneNumber} from '@src/lib/PhoneNumberParser';
import {addCommaToNumber} from '@src/lib/NumberParser';

export const placementColumns = [
  {
    title: '주문번호',
    dataIndex: 'orderMerchantUid',
    key: 'orderMerchantUid',
    sorter: (a, b) => b.orderMerchantUid - a.orderMerchantUid,
    width: 150,
    ellipsis: true,
  },
  {
    title: '상품주문번호',
    dataIndex: 'merchantUid',
    key: 'merchantUid',
    sorter: (a, b) => b.merchantUid - a.merchantUid,
    width: 150,
    ellipsis: true,
  },
  {
    title: '상품번호',
    dataIndex: 'productSku',
    key: 'productSku',
    sorter: (a, b) => b.productSku - a.productSku,
    width: 100,
    ellipsis: true,
  },
  {
    title: '주문일시',
    dataIndex: 'paidAt',
    key: 'paidAt',
    render: value => {
      const {year, month, day} = getDateTimeStrings(value);
      return <div>{`${year}.${month}.${day}`}</div>;
    },
    sorter: (a, b) => b.paidAt - a.paidAt,
    width: 100,
    ellipsis: true,
  },
  {
    title: '주문상태',
    dataIndex: 'status',
    key: 'status',
    sorter: (a, b) => b.status - a.status,
    width: 100,
    ellipsis: true,
  },
  {
    title: '상품명',
    dataIndex: 'itemName',
    key: 'itemName',
    sorter: (a, b) => b.itemName - a.itemName,
    width: 150,
    ellipsis: true,
  },
  {
    title: '옵션(통합)',
    dataIndex: 'options',
    key: 'options',
    render: value => value.join('-'),
    sorter: (a, b) => b.options.join('-') - a.options.join('-'),
    width: 100,
    ellipsis: true,
  },
  {
    title: '수량',
    dataIndex: 'quantity',
    key: 'quantity',
    sorter: (a, b) => b.quantity - a.quantity,
    width: 75,
    ellipsis: true,
  },
  {
    title: '구매자명',
    dataIndex: 'buyerName',
    key: 'buyerName',
    sorter: (a, b) => b.buyerName - a.buyerName,
    width: 100,
    ellipsis: true,
  },
  {
    title: '구매자 연락처',
    dataIndex: 'buyerPhone',
    key: 'buyerPhone',
    render: value => <div>{value ? addDashToPhoneNumber(value) : null}</div>,
    sorter: (a, b) => b.buyerPhone - a.buyerPhone,
    width: 125,
    ellipsis: true,
  },
  {
    title: '구매자 이메일',
    dataIndex: 'buyerEmail',
    key: 'buyerEmail',
    sorter: (a, b) => b.buyerEmail - a.buyerEmail,
    width: 175,
    ellipsis: true,
  },
  {
    title: '수취인명',
    dataIndex: 'addressName',
    key: 'addressName',
    sorter: (a, b) => b.addressName - a.addressName,
    width: 75,
    ellipsis: true,
  },
  {
    title: '수취인 연락처',
    dataIndex: 'addressPhone',
    key: 'addressPhone',
    render: value => <div>{value ? addDashToPhoneNumber(value) : null}</div>,
    sorter: (a, b) => b.addressPhone - a.addressPhone,
    width: 125,
    ellipsis: true,
  },
  {
    title: '우편번호',
    dataIndex: 'addressPostCode',
    key: 'addressPostCode',
    sorter: (a, b) => b.addressPostCode - a.addressPostCode,
    width: 75,
    ellipsis: true,
  },
  {
    title: '배송지 주소',
    dataIndex: 'baseAddress',
    key: 'baseAddress',
    sorter: (a, b) => b.baseAddress - a.baseAddress,
    width: 150,
    ellipsis: true,
  },
  {
    title: '배송지 상세주소',
    dataIndex: 'detailAddress',
    key: 'detailAddress',
    sorter: (a, b) => b.detailAddress - a.detailAddress,
    width: 150,
    ellipsis: true,
  },
  {
    title: '배송메세지',
    dataIndex: 'addressMessage',
    key: 'addressMessage',
    sorter: (a, b) => b.addressMessage - a.addressMessage,
    width: 150,
    ellipsis: true,
  },
  {
    title: '택배사',
    dataIndex: 'courier',
    key: 'courier',
    sorter: (a, b) => b.courier - a.courier,
    width: 100,
    ellipsis: true,
  },
  {
    title: '송장번호',
    dataIndex: 'trackingCode',
    key: 'trackingCode',
    sorter: (a, b) => b.trackingCode - a.trackingCode,
    width: 150,
    ellipsis: true,
  },
  {
    title: '배송추적',
    dataIndex: 'trackingViewUrl',
    key: 'trackingViewUrl',
    render: value =>
      value ? (
        <a href={value} target="_blank">
          <Button size="small">배송추적</Button>
        </a>
      ) : null,
    sorter: (a, b) => b.trackingViewUrl - a.trackingViewUrl,
    width: 100,
    ellipsis: true,
  },
  {
    title: '판매가격',
    dataIndex: 'salePrice',
    key: 'salePrice',
    render: value => <div>{addCommaToNumber(value)}원</div>,
    sorter: (a, b) => b.salePrice - a.salePrice,
    width: 100,
    ellipsis: true,
  },
  {
    title: '리뷰어',
    dataIndex: 'reviewer',
    key: 'reviewer',
    sorter: (a, b) => b.reviewer - a.reviewer,
    width: 100,
    ellipsis: true,
  },
  {
    title: '구독할인율',
    dataIndex: 'subDiscountRate',
    key: 'subDiscountRate',
    render: value => <div>{value}%</div>,
    sorter: (a, b) => b.subDiscountRate - a.subDiscountRate,
    width: 100,
    ellipsis: true,
  },
];
